#!/usr/bin/env bash

echo "
-------------------------------------------------------------------------------
ZK NFT Deployment Script
-------------------------------------------------------------------------------
This script deploys an instance of ZK-NFT contract with the zkSNARK verifier in `src/verifier.sol` 

Prerequisites:
* This script uses the Seth Ethereum CLI which can be installed from http://dapp.tools by running `curl https://dapp.tools/install | sh`
* Set the variable ANCHOR_REPOSITORY to an instance of the Centrifuge Anchor Repository (https://github.com/centrifuge/centrifuge-ethereum-contracts/blob/develop/contracts/AnchorRepository.sol). 
* If you want to use an existing deployment of the anchor registry, they can be found here: https://github.com/centrifuge/go-centrifuge/blob/develop/build/configs/default_config.yaml

"
set -ex

REGISTRY=$(seth send --create out/ZKNFT.bin 'ZKNFT(string memory, string memory, address)' "Private Payment Obligation" "ZKNFT" $ANCHOR_REPOSITORY)

set +ex
echo "-------------------------------------------------------------------------------"
echo "NFT registry deployed to: $REGISTRY"
echo "-------------------------------------------------------------------------------"
